/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Aeronaves: () => import('#controllers/aeronaves_controller'),
  Alunos: () => import('#controllers/alunos_controller'),
  Barras: () => import('#controllers/barras_controller'),
  Bases: () => import('#controllers/bases_controller'),
  Cursos: () => import('#controllers/cursos_controller'),
  EscalaTrabalhos: () => import('#controllers/escala_trabalhos_controller'),
  Invas: () => import('#controllers/invas_controller'),
  Missoes: () => import('#controllers/missoes_controller'),
  ModeloAeronaves: () => import('#controllers/modelo_aeronaves_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Restricoes: () => import('#controllers/restricoes_controller'),
  SituacaoInvas: () => import('#controllers/situacao_invas_controller'),
  Slots: () => import('#controllers/slots_controller'),
  StatusSlots: () => import('#controllers/status_slots_controller'),
  TipoDisponibilidades: () => import('#controllers/tipo_disponibilidades_controller'),
  Users: () => import('#controllers/users_controller'),
}
