/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AeronaveSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'modeloAeronaveId', 'nome', 'updatedAt'] as const
  $columns = AeronaveSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare modeloAeronaveId: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AlunoSchema extends BaseModel {
  static $columns = ['celular', 'cpf', 'createdAt', 'id', 'nome', 'updatedAt'] as const
  $columns = AlunoSchema.$columns
  @column()
  declare celular: string | null
  @column()
  declare cpf: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BarraSchema extends BaseModel {
  static $columns = ['baseId', 'createdAt', 'id', 'modeloAeronaveId', 'nome', 'updatedAt'] as const
  $columns = BarraSchema.$columns
  @column()
  declare baseId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare modeloAeronaveId: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BaseSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nome', 'updatedAt'] as const
  $columns = BaseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CursoSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nome', 'updatedAt'] as const
  $columns = CursoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvaSchema extends BaseModel {
  static $columns = ['baseId', 'celular', 'createdAt', 'id', 'nome', 'situacaoInvaId', 'updatedAt'] as const
  $columns = InvaSchema.$columns
  @column()
  declare baseId: number | null
  @column()
  declare celular: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column()
  declare situacaoInvaId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MissoeSchema extends BaseModel {
  static $columns = ['createdAt', 'cursoId', 'id', 'nome', 'updatedAt'] as const
  $columns = MissoeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cursoId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModelosAeronaveSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nome', 'updatedAt'] as const
  $columns = ModelosAeronaveSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RestricoeSchema extends BaseModel {
  static $columns = ['aeronaveId', 'alunoId', 'createdAt', 'id', 'invaId', 'isAeronave', 'isAluno', 'isAlunoInva', 'isInva', 'isMissao', 'isModelo', 'missaoId', 'modeloAeronaveId', 'nome', 'observacao', 'updatedAt'] as const
  $columns = RestricoeSchema.$columns
  @column()
  declare aeronaveId: number | null
  @column()
  declare alunoId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invaId: number | null
  @column()
  declare isAeronave: boolean | null
  @column()
  declare isAluno: boolean | null
  @column()
  declare isAlunoInva: boolean | null
  @column()
  declare isInva: boolean | null
  @column()
  declare isMissao: boolean | null
  @column()
  declare isModelo: boolean | null
  @column()
  declare missaoId: number | null
  @column()
  declare modeloAeronaveId: number | null
  @column()
  declare nome: string | null
  @column()
  declare observacao: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SituacoesInvaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nome', 'updatedAt'] as const
  $columns = SituacoesInvaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SlotSchema extends BaseModel {
  static $columns = ['aeronaveId', 'alunoId', 'barraId', 'createdAt', 'dataHora', 'id', 'invaId', 'isChecked', 'missaoId', 'observacoes', 'statusSlotId', 'updatedAt'] as const
  $columns = SlotSchema.$columns
  @column()
  declare aeronaveId: number | null
  @column()
  declare alunoId: number | null
  @column()
  declare barraId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dataHora: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invaId: number | null
  @column()
  declare isChecked: boolean
  @column()
  declare missaoId: number | null
  @column()
  declare observacoes: string | null
  @column()
  declare statusSlotId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StatusSlotSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nome', 'updatedAt'] as const
  $columns = StatusSlotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
