/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.new_account.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/signup',
    tokens: [{"old":"/api/v1/auth/signup","type":0,"val":"api","end":""},{"old":"/api/v1/auth/signup","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/signup","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['auth.new_account.store']['types'],
  },
  'auth.access_tokens.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.access_tokens.store']['types'],
  },
  'profile.profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/account/profile',
    tokens: [{"old":"/account/profile","type":0,"val":"account","end":""},{"old":"/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.profile.show']['types'],
  },
  'profile.access_tokens.destroy': {
    methods: ["POST"],
    pattern: '/account/logout',
    tokens: [{"old":"/account/logout","type":0,"val":"account","end":""},{"old":"/account/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['profile.access_tokens.destroy']['types'],
  },
  'users.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users',
    tokens: [{"old":"/api/v1/users","type":0,"val":"api","end":""},{"old":"/api/v1/users","type":0,"val":"v1","end":""},{"old":"/api/v1/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.index']['types'],
  },
  'users.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users/create',
    tokens: [{"old":"/api/v1/users/create","type":0,"val":"api","end":""},{"old":"/api/v1/users/create","type":0,"val":"v1","end":""},{"old":"/api/v1/users/create","type":0,"val":"users","end":""},{"old":"/api/v1/users/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['users.create']['types'],
  },
  'users.store': {
    methods: ["POST"],
    pattern: '/api/v1/users',
    tokens: [{"old":"/api/v1/users","type":0,"val":"api","end":""},{"old":"/api/v1/users","type":0,"val":"v1","end":""},{"old":"/api/v1/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.store']['types'],
  },
  'users.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.show']['types'],
  },
  'users.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users/:id/edit',
    tokens: [{"old":"/api/v1/users/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id/edit","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/users/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['users.edit']['types'],
  },
  'users.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.update']['types'],
  },
  'users.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.destroy']['types'],
  },
  'situacao_invas.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/situacao-invas',
    tokens: [{"old":"/api/v1/situacao-invas","type":0,"val":"api","end":""},{"old":"/api/v1/situacao-invas","type":0,"val":"v1","end":""},{"old":"/api/v1/situacao-invas","type":0,"val":"situacao-invas","end":""}],
    types: placeholder as Registry['situacao_invas.index']['types'],
  },
  'situacao_invas.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/situacao-invas/create',
    tokens: [{"old":"/api/v1/situacao-invas/create","type":0,"val":"api","end":""},{"old":"/api/v1/situacao-invas/create","type":0,"val":"v1","end":""},{"old":"/api/v1/situacao-invas/create","type":0,"val":"situacao-invas","end":""},{"old":"/api/v1/situacao-invas/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['situacao_invas.create']['types'],
  },
  'situacao_invas.store': {
    methods: ["POST"],
    pattern: '/api/v1/situacao-invas',
    tokens: [{"old":"/api/v1/situacao-invas","type":0,"val":"api","end":""},{"old":"/api/v1/situacao-invas","type":0,"val":"v1","end":""},{"old":"/api/v1/situacao-invas","type":0,"val":"situacao-invas","end":""}],
    types: placeholder as Registry['situacao_invas.store']['types'],
  },
  'situacao_invas.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/situacao-invas/:id',
    tokens: [{"old":"/api/v1/situacao-invas/:id","type":0,"val":"api","end":""},{"old":"/api/v1/situacao-invas/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/situacao-invas/:id","type":0,"val":"situacao-invas","end":""},{"old":"/api/v1/situacao-invas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['situacao_invas.show']['types'],
  },
  'situacao_invas.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/situacao-invas/:id/edit',
    tokens: [{"old":"/api/v1/situacao-invas/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/situacao-invas/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/situacao-invas/:id/edit","type":0,"val":"situacao-invas","end":""},{"old":"/api/v1/situacao-invas/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/situacao-invas/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['situacao_invas.edit']['types'],
  },
  'situacao_invas.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/situacao-invas/:id',
    tokens: [{"old":"/api/v1/situacao-invas/:id","type":0,"val":"api","end":""},{"old":"/api/v1/situacao-invas/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/situacao-invas/:id","type":0,"val":"situacao-invas","end":""},{"old":"/api/v1/situacao-invas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['situacao_invas.update']['types'],
  },
  'situacao_invas.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/situacao-invas/:id',
    tokens: [{"old":"/api/v1/situacao-invas/:id","type":0,"val":"api","end":""},{"old":"/api/v1/situacao-invas/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/situacao-invas/:id","type":0,"val":"situacao-invas","end":""},{"old":"/api/v1/situacao-invas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['situacao_invas.destroy']['types'],
  },
  'modelo_aeronaves.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/modelo-aeronaves',
    tokens: [{"old":"/api/v1/modelo-aeronaves","type":0,"val":"api","end":""},{"old":"/api/v1/modelo-aeronaves","type":0,"val":"v1","end":""},{"old":"/api/v1/modelo-aeronaves","type":0,"val":"modelo-aeronaves","end":""}],
    types: placeholder as Registry['modelo_aeronaves.index']['types'],
  },
  'modelo_aeronaves.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/modelo-aeronaves/create',
    tokens: [{"old":"/api/v1/modelo-aeronaves/create","type":0,"val":"api","end":""},{"old":"/api/v1/modelo-aeronaves/create","type":0,"val":"v1","end":""},{"old":"/api/v1/modelo-aeronaves/create","type":0,"val":"modelo-aeronaves","end":""},{"old":"/api/v1/modelo-aeronaves/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['modelo_aeronaves.create']['types'],
  },
  'modelo_aeronaves.store': {
    methods: ["POST"],
    pattern: '/api/v1/modelo-aeronaves',
    tokens: [{"old":"/api/v1/modelo-aeronaves","type":0,"val":"api","end":""},{"old":"/api/v1/modelo-aeronaves","type":0,"val":"v1","end":""},{"old":"/api/v1/modelo-aeronaves","type":0,"val":"modelo-aeronaves","end":""}],
    types: placeholder as Registry['modelo_aeronaves.store']['types'],
  },
  'modelo_aeronaves.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/modelo-aeronaves/:id',
    tokens: [{"old":"/api/v1/modelo-aeronaves/:id","type":0,"val":"api","end":""},{"old":"/api/v1/modelo-aeronaves/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/modelo-aeronaves/:id","type":0,"val":"modelo-aeronaves","end":""},{"old":"/api/v1/modelo-aeronaves/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['modelo_aeronaves.show']['types'],
  },
  'modelo_aeronaves.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/modelo-aeronaves/:id/edit',
    tokens: [{"old":"/api/v1/modelo-aeronaves/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/modelo-aeronaves/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/modelo-aeronaves/:id/edit","type":0,"val":"modelo-aeronaves","end":""},{"old":"/api/v1/modelo-aeronaves/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/modelo-aeronaves/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['modelo_aeronaves.edit']['types'],
  },
  'modelo_aeronaves.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/modelo-aeronaves/:id',
    tokens: [{"old":"/api/v1/modelo-aeronaves/:id","type":0,"val":"api","end":""},{"old":"/api/v1/modelo-aeronaves/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/modelo-aeronaves/:id","type":0,"val":"modelo-aeronaves","end":""},{"old":"/api/v1/modelo-aeronaves/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['modelo_aeronaves.update']['types'],
  },
  'modelo_aeronaves.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/modelo-aeronaves/:id',
    tokens: [{"old":"/api/v1/modelo-aeronaves/:id","type":0,"val":"api","end":""},{"old":"/api/v1/modelo-aeronaves/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/modelo-aeronaves/:id","type":0,"val":"modelo-aeronaves","end":""},{"old":"/api/v1/modelo-aeronaves/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['modelo_aeronaves.destroy']['types'],
  },
  'bases.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/bases',
    tokens: [{"old":"/api/v1/bases","type":0,"val":"api","end":""},{"old":"/api/v1/bases","type":0,"val":"v1","end":""},{"old":"/api/v1/bases","type":0,"val":"bases","end":""}],
    types: placeholder as Registry['bases.index']['types'],
  },
  'bases.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/bases/create',
    tokens: [{"old":"/api/v1/bases/create","type":0,"val":"api","end":""},{"old":"/api/v1/bases/create","type":0,"val":"v1","end":""},{"old":"/api/v1/bases/create","type":0,"val":"bases","end":""},{"old":"/api/v1/bases/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['bases.create']['types'],
  },
  'bases.store': {
    methods: ["POST"],
    pattern: '/api/v1/bases',
    tokens: [{"old":"/api/v1/bases","type":0,"val":"api","end":""},{"old":"/api/v1/bases","type":0,"val":"v1","end":""},{"old":"/api/v1/bases","type":0,"val":"bases","end":""}],
    types: placeholder as Registry['bases.store']['types'],
  },
  'bases.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/bases/:id',
    tokens: [{"old":"/api/v1/bases/:id","type":0,"val":"api","end":""},{"old":"/api/v1/bases/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/bases/:id","type":0,"val":"bases","end":""},{"old":"/api/v1/bases/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bases.show']['types'],
  },
  'bases.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/bases/:id/edit',
    tokens: [{"old":"/api/v1/bases/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/bases/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/bases/:id/edit","type":0,"val":"bases","end":""},{"old":"/api/v1/bases/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/bases/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['bases.edit']['types'],
  },
  'bases.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/bases/:id',
    tokens: [{"old":"/api/v1/bases/:id","type":0,"val":"api","end":""},{"old":"/api/v1/bases/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/bases/:id","type":0,"val":"bases","end":""},{"old":"/api/v1/bases/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bases.update']['types'],
  },
  'bases.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/bases/:id',
    tokens: [{"old":"/api/v1/bases/:id","type":0,"val":"api","end":""},{"old":"/api/v1/bases/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/bases/:id","type":0,"val":"bases","end":""},{"old":"/api/v1/bases/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bases.destroy']['types'],
  },
  'status_slots.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/status-slots',
    tokens: [{"old":"/api/v1/status-slots","type":0,"val":"api","end":""},{"old":"/api/v1/status-slots","type":0,"val":"v1","end":""},{"old":"/api/v1/status-slots","type":0,"val":"status-slots","end":""}],
    types: placeholder as Registry['status_slots.index']['types'],
  },
  'status_slots.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/status-slots/create',
    tokens: [{"old":"/api/v1/status-slots/create","type":0,"val":"api","end":""},{"old":"/api/v1/status-slots/create","type":0,"val":"v1","end":""},{"old":"/api/v1/status-slots/create","type":0,"val":"status-slots","end":""},{"old":"/api/v1/status-slots/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['status_slots.create']['types'],
  },
  'status_slots.store': {
    methods: ["POST"],
    pattern: '/api/v1/status-slots',
    tokens: [{"old":"/api/v1/status-slots","type":0,"val":"api","end":""},{"old":"/api/v1/status-slots","type":0,"val":"v1","end":""},{"old":"/api/v1/status-slots","type":0,"val":"status-slots","end":""}],
    types: placeholder as Registry['status_slots.store']['types'],
  },
  'status_slots.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/status-slots/:id',
    tokens: [{"old":"/api/v1/status-slots/:id","type":0,"val":"api","end":""},{"old":"/api/v1/status-slots/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/status-slots/:id","type":0,"val":"status-slots","end":""},{"old":"/api/v1/status-slots/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['status_slots.show']['types'],
  },
  'status_slots.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/status-slots/:id/edit',
    tokens: [{"old":"/api/v1/status-slots/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/status-slots/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/status-slots/:id/edit","type":0,"val":"status-slots","end":""},{"old":"/api/v1/status-slots/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/status-slots/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['status_slots.edit']['types'],
  },
  'status_slots.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/status-slots/:id',
    tokens: [{"old":"/api/v1/status-slots/:id","type":0,"val":"api","end":""},{"old":"/api/v1/status-slots/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/status-slots/:id","type":0,"val":"status-slots","end":""},{"old":"/api/v1/status-slots/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['status_slots.update']['types'],
  },
  'status_slots.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/status-slots/:id',
    tokens: [{"old":"/api/v1/status-slots/:id","type":0,"val":"api","end":""},{"old":"/api/v1/status-slots/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/status-slots/:id","type":0,"val":"status-slots","end":""},{"old":"/api/v1/status-slots/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['status_slots.destroy']['types'],
  },
  'cursos.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cursos',
    tokens: [{"old":"/api/v1/cursos","type":0,"val":"api","end":""},{"old":"/api/v1/cursos","type":0,"val":"v1","end":""},{"old":"/api/v1/cursos","type":0,"val":"cursos","end":""}],
    types: placeholder as Registry['cursos.index']['types'],
  },
  'cursos.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cursos/create',
    tokens: [{"old":"/api/v1/cursos/create","type":0,"val":"api","end":""},{"old":"/api/v1/cursos/create","type":0,"val":"v1","end":""},{"old":"/api/v1/cursos/create","type":0,"val":"cursos","end":""},{"old":"/api/v1/cursos/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['cursos.create']['types'],
  },
  'cursos.store': {
    methods: ["POST"],
    pattern: '/api/v1/cursos',
    tokens: [{"old":"/api/v1/cursos","type":0,"val":"api","end":""},{"old":"/api/v1/cursos","type":0,"val":"v1","end":""},{"old":"/api/v1/cursos","type":0,"val":"cursos","end":""}],
    types: placeholder as Registry['cursos.store']['types'],
  },
  'cursos.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cursos/:id',
    tokens: [{"old":"/api/v1/cursos/:id","type":0,"val":"api","end":""},{"old":"/api/v1/cursos/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/cursos/:id","type":0,"val":"cursos","end":""},{"old":"/api/v1/cursos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cursos.show']['types'],
  },
  'cursos.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cursos/:id/edit',
    tokens: [{"old":"/api/v1/cursos/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/cursos/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/cursos/:id/edit","type":0,"val":"cursos","end":""},{"old":"/api/v1/cursos/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/cursos/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['cursos.edit']['types'],
  },
  'cursos.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/cursos/:id',
    tokens: [{"old":"/api/v1/cursos/:id","type":0,"val":"api","end":""},{"old":"/api/v1/cursos/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/cursos/:id","type":0,"val":"cursos","end":""},{"old":"/api/v1/cursos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cursos.update']['types'],
  },
  'cursos.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/cursos/:id',
    tokens: [{"old":"/api/v1/cursos/:id","type":0,"val":"api","end":""},{"old":"/api/v1/cursos/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/cursos/:id","type":0,"val":"cursos","end":""},{"old":"/api/v1/cursos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cursos.destroy']['types'],
  },
  'aeronaves.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/aeronaves',
    tokens: [{"old":"/api/v1/aeronaves","type":0,"val":"api","end":""},{"old":"/api/v1/aeronaves","type":0,"val":"v1","end":""},{"old":"/api/v1/aeronaves","type":0,"val":"aeronaves","end":""}],
    types: placeholder as Registry['aeronaves.index']['types'],
  },
  'aeronaves.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/aeronaves/create',
    tokens: [{"old":"/api/v1/aeronaves/create","type":0,"val":"api","end":""},{"old":"/api/v1/aeronaves/create","type":0,"val":"v1","end":""},{"old":"/api/v1/aeronaves/create","type":0,"val":"aeronaves","end":""},{"old":"/api/v1/aeronaves/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['aeronaves.create']['types'],
  },
  'aeronaves.store': {
    methods: ["POST"],
    pattern: '/api/v1/aeronaves',
    tokens: [{"old":"/api/v1/aeronaves","type":0,"val":"api","end":""},{"old":"/api/v1/aeronaves","type":0,"val":"v1","end":""},{"old":"/api/v1/aeronaves","type":0,"val":"aeronaves","end":""}],
    types: placeholder as Registry['aeronaves.store']['types'],
  },
  'aeronaves.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/aeronaves/:id',
    tokens: [{"old":"/api/v1/aeronaves/:id","type":0,"val":"api","end":""},{"old":"/api/v1/aeronaves/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/aeronaves/:id","type":0,"val":"aeronaves","end":""},{"old":"/api/v1/aeronaves/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['aeronaves.show']['types'],
  },
  'aeronaves.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/aeronaves/:id/edit',
    tokens: [{"old":"/api/v1/aeronaves/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/aeronaves/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/aeronaves/:id/edit","type":0,"val":"aeronaves","end":""},{"old":"/api/v1/aeronaves/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/aeronaves/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['aeronaves.edit']['types'],
  },
  'aeronaves.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/aeronaves/:id',
    tokens: [{"old":"/api/v1/aeronaves/:id","type":0,"val":"api","end":""},{"old":"/api/v1/aeronaves/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/aeronaves/:id","type":0,"val":"aeronaves","end":""},{"old":"/api/v1/aeronaves/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['aeronaves.update']['types'],
  },
  'aeronaves.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/aeronaves/:id',
    tokens: [{"old":"/api/v1/aeronaves/:id","type":0,"val":"api","end":""},{"old":"/api/v1/aeronaves/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/aeronaves/:id","type":0,"val":"aeronaves","end":""},{"old":"/api/v1/aeronaves/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['aeronaves.destroy']['types'],
  },
  'missoes.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/missoes',
    tokens: [{"old":"/api/v1/missoes","type":0,"val":"api","end":""},{"old":"/api/v1/missoes","type":0,"val":"v1","end":""},{"old":"/api/v1/missoes","type":0,"val":"missoes","end":""}],
    types: placeholder as Registry['missoes.index']['types'],
  },
  'missoes.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/missoes/create',
    tokens: [{"old":"/api/v1/missoes/create","type":0,"val":"api","end":""},{"old":"/api/v1/missoes/create","type":0,"val":"v1","end":""},{"old":"/api/v1/missoes/create","type":0,"val":"missoes","end":""},{"old":"/api/v1/missoes/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['missoes.create']['types'],
  },
  'missoes.store': {
    methods: ["POST"],
    pattern: '/api/v1/missoes',
    tokens: [{"old":"/api/v1/missoes","type":0,"val":"api","end":""},{"old":"/api/v1/missoes","type":0,"val":"v1","end":""},{"old":"/api/v1/missoes","type":0,"val":"missoes","end":""}],
    types: placeholder as Registry['missoes.store']['types'],
  },
  'missoes.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/missoes/:id',
    tokens: [{"old":"/api/v1/missoes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/missoes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/missoes/:id","type":0,"val":"missoes","end":""},{"old":"/api/v1/missoes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['missoes.show']['types'],
  },
  'missoes.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/missoes/:id/edit',
    tokens: [{"old":"/api/v1/missoes/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/missoes/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/missoes/:id/edit","type":0,"val":"missoes","end":""},{"old":"/api/v1/missoes/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/missoes/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['missoes.edit']['types'],
  },
  'missoes.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/missoes/:id',
    tokens: [{"old":"/api/v1/missoes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/missoes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/missoes/:id","type":0,"val":"missoes","end":""},{"old":"/api/v1/missoes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['missoes.update']['types'],
  },
  'missoes.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/missoes/:id',
    tokens: [{"old":"/api/v1/missoes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/missoes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/missoes/:id","type":0,"val":"missoes","end":""},{"old":"/api/v1/missoes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['missoes.destroy']['types'],
  },
  'invas.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invas',
    tokens: [{"old":"/api/v1/invas","type":0,"val":"api","end":""},{"old":"/api/v1/invas","type":0,"val":"v1","end":""},{"old":"/api/v1/invas","type":0,"val":"invas","end":""}],
    types: placeholder as Registry['invas.index']['types'],
  },
  'invas.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invas/create',
    tokens: [{"old":"/api/v1/invas/create","type":0,"val":"api","end":""},{"old":"/api/v1/invas/create","type":0,"val":"v1","end":""},{"old":"/api/v1/invas/create","type":0,"val":"invas","end":""},{"old":"/api/v1/invas/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['invas.create']['types'],
  },
  'invas.store': {
    methods: ["POST"],
    pattern: '/api/v1/invas',
    tokens: [{"old":"/api/v1/invas","type":0,"val":"api","end":""},{"old":"/api/v1/invas","type":0,"val":"v1","end":""},{"old":"/api/v1/invas","type":0,"val":"invas","end":""}],
    types: placeholder as Registry['invas.store']['types'],
  },
  'invas.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invas/:id',
    tokens: [{"old":"/api/v1/invas/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invas/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invas/:id","type":0,"val":"invas","end":""},{"old":"/api/v1/invas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invas.show']['types'],
  },
  'invas.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invas/:id/edit',
    tokens: [{"old":"/api/v1/invas/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/invas/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/invas/:id/edit","type":0,"val":"invas","end":""},{"old":"/api/v1/invas/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/invas/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['invas.edit']['types'],
  },
  'invas.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/invas/:id',
    tokens: [{"old":"/api/v1/invas/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invas/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invas/:id","type":0,"val":"invas","end":""},{"old":"/api/v1/invas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invas.update']['types'],
  },
  'invas.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/invas/:id',
    tokens: [{"old":"/api/v1/invas/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invas/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invas/:id","type":0,"val":"invas","end":""},{"old":"/api/v1/invas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invas.destroy']['types'],
  },
  'alunos.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/alunos',
    tokens: [{"old":"/api/v1/alunos","type":0,"val":"api","end":""},{"old":"/api/v1/alunos","type":0,"val":"v1","end":""},{"old":"/api/v1/alunos","type":0,"val":"alunos","end":""}],
    types: placeholder as Registry['alunos.index']['types'],
  },
  'alunos.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/alunos/create',
    tokens: [{"old":"/api/v1/alunos/create","type":0,"val":"api","end":""},{"old":"/api/v1/alunos/create","type":0,"val":"v1","end":""},{"old":"/api/v1/alunos/create","type":0,"val":"alunos","end":""},{"old":"/api/v1/alunos/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['alunos.create']['types'],
  },
  'alunos.store': {
    methods: ["POST"],
    pattern: '/api/v1/alunos',
    tokens: [{"old":"/api/v1/alunos","type":0,"val":"api","end":""},{"old":"/api/v1/alunos","type":0,"val":"v1","end":""},{"old":"/api/v1/alunos","type":0,"val":"alunos","end":""}],
    types: placeholder as Registry['alunos.store']['types'],
  },
  'alunos.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/alunos/:id',
    tokens: [{"old":"/api/v1/alunos/:id","type":0,"val":"api","end":""},{"old":"/api/v1/alunos/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/alunos/:id","type":0,"val":"alunos","end":""},{"old":"/api/v1/alunos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['alunos.show']['types'],
  },
  'alunos.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/alunos/:id/edit',
    tokens: [{"old":"/api/v1/alunos/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/alunos/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/alunos/:id/edit","type":0,"val":"alunos","end":""},{"old":"/api/v1/alunos/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/alunos/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['alunos.edit']['types'],
  },
  'alunos.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/alunos/:id',
    tokens: [{"old":"/api/v1/alunos/:id","type":0,"val":"api","end":""},{"old":"/api/v1/alunos/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/alunos/:id","type":0,"val":"alunos","end":""},{"old":"/api/v1/alunos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['alunos.update']['types'],
  },
  'alunos.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/alunos/:id',
    tokens: [{"old":"/api/v1/alunos/:id","type":0,"val":"api","end":""},{"old":"/api/v1/alunos/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/alunos/:id","type":0,"val":"alunos","end":""},{"old":"/api/v1/alunos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['alunos.destroy']['types'],
  },
  'restricoes.import': {
    methods: ["POST"],
    pattern: '/api/v1/restricoes/import',
    tokens: [{"old":"/api/v1/restricoes/import","type":0,"val":"api","end":""},{"old":"/api/v1/restricoes/import","type":0,"val":"v1","end":""},{"old":"/api/v1/restricoes/import","type":0,"val":"restricoes","end":""},{"old":"/api/v1/restricoes/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['restricoes.import']['types'],
  },
  'restricoes.bulk_destroy': {
    methods: ["POST"],
    pattern: '/api/v1/restricoes/bulk-delete',
    tokens: [{"old":"/api/v1/restricoes/bulk-delete","type":0,"val":"api","end":""},{"old":"/api/v1/restricoes/bulk-delete","type":0,"val":"v1","end":""},{"old":"/api/v1/restricoes/bulk-delete","type":0,"val":"restricoes","end":""},{"old":"/api/v1/restricoes/bulk-delete","type":0,"val":"bulk-delete","end":""}],
    types: placeholder as Registry['restricoes.bulk_destroy']['types'],
  },
  'restricoes.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/restricoes',
    tokens: [{"old":"/api/v1/restricoes","type":0,"val":"api","end":""},{"old":"/api/v1/restricoes","type":0,"val":"v1","end":""},{"old":"/api/v1/restricoes","type":0,"val":"restricoes","end":""}],
    types: placeholder as Registry['restricoes.index']['types'],
  },
  'restricoes.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/restricoes/create',
    tokens: [{"old":"/api/v1/restricoes/create","type":0,"val":"api","end":""},{"old":"/api/v1/restricoes/create","type":0,"val":"v1","end":""},{"old":"/api/v1/restricoes/create","type":0,"val":"restricoes","end":""},{"old":"/api/v1/restricoes/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['restricoes.create']['types'],
  },
  'restricoes.store': {
    methods: ["POST"],
    pattern: '/api/v1/restricoes',
    tokens: [{"old":"/api/v1/restricoes","type":0,"val":"api","end":""},{"old":"/api/v1/restricoes","type":0,"val":"v1","end":""},{"old":"/api/v1/restricoes","type":0,"val":"restricoes","end":""}],
    types: placeholder as Registry['restricoes.store']['types'],
  },
  'restricoes.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/restricoes/:id',
    tokens: [{"old":"/api/v1/restricoes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/restricoes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/restricoes/:id","type":0,"val":"restricoes","end":""},{"old":"/api/v1/restricoes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['restricoes.show']['types'],
  },
  'restricoes.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/restricoes/:id/edit',
    tokens: [{"old":"/api/v1/restricoes/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/restricoes/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/restricoes/:id/edit","type":0,"val":"restricoes","end":""},{"old":"/api/v1/restricoes/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/restricoes/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['restricoes.edit']['types'],
  },
  'restricoes.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/restricoes/:id',
    tokens: [{"old":"/api/v1/restricoes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/restricoes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/restricoes/:id","type":0,"val":"restricoes","end":""},{"old":"/api/v1/restricoes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['restricoes.update']['types'],
  },
  'restricoes.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/restricoes/:id',
    tokens: [{"old":"/api/v1/restricoes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/restricoes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/restricoes/:id","type":0,"val":"restricoes","end":""},{"old":"/api/v1/restricoes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['restricoes.destroy']['types'],
  },
  'tipo_disponibilidades.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tipo-disponibilidades',
    tokens: [{"old":"/api/v1/tipo-disponibilidades","type":0,"val":"api","end":""},{"old":"/api/v1/tipo-disponibilidades","type":0,"val":"v1","end":""},{"old":"/api/v1/tipo-disponibilidades","type":0,"val":"tipo-disponibilidades","end":""}],
    types: placeholder as Registry['tipo_disponibilidades.index']['types'],
  },
  'tipo_disponibilidades.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tipo-disponibilidades/create',
    tokens: [{"old":"/api/v1/tipo-disponibilidades/create","type":0,"val":"api","end":""},{"old":"/api/v1/tipo-disponibilidades/create","type":0,"val":"v1","end":""},{"old":"/api/v1/tipo-disponibilidades/create","type":0,"val":"tipo-disponibilidades","end":""},{"old":"/api/v1/tipo-disponibilidades/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['tipo_disponibilidades.create']['types'],
  },
  'tipo_disponibilidades.store': {
    methods: ["POST"],
    pattern: '/api/v1/tipo-disponibilidades',
    tokens: [{"old":"/api/v1/tipo-disponibilidades","type":0,"val":"api","end":""},{"old":"/api/v1/tipo-disponibilidades","type":0,"val":"v1","end":""},{"old":"/api/v1/tipo-disponibilidades","type":0,"val":"tipo-disponibilidades","end":""}],
    types: placeholder as Registry['tipo_disponibilidades.store']['types'],
  },
  'tipo_disponibilidades.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tipo-disponibilidades/:id',
    tokens: [{"old":"/api/v1/tipo-disponibilidades/:id","type":0,"val":"api","end":""},{"old":"/api/v1/tipo-disponibilidades/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/tipo-disponibilidades/:id","type":0,"val":"tipo-disponibilidades","end":""},{"old":"/api/v1/tipo-disponibilidades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tipo_disponibilidades.show']['types'],
  },
  'tipo_disponibilidades.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tipo-disponibilidades/:id/edit',
    tokens: [{"old":"/api/v1/tipo-disponibilidades/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/tipo-disponibilidades/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/tipo-disponibilidades/:id/edit","type":0,"val":"tipo-disponibilidades","end":""},{"old":"/api/v1/tipo-disponibilidades/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/tipo-disponibilidades/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['tipo_disponibilidades.edit']['types'],
  },
  'tipo_disponibilidades.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/tipo-disponibilidades/:id',
    tokens: [{"old":"/api/v1/tipo-disponibilidades/:id","type":0,"val":"api","end":""},{"old":"/api/v1/tipo-disponibilidades/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/tipo-disponibilidades/:id","type":0,"val":"tipo-disponibilidades","end":""},{"old":"/api/v1/tipo-disponibilidades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tipo_disponibilidades.update']['types'],
  },
  'tipo_disponibilidades.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/tipo-disponibilidades/:id',
    tokens: [{"old":"/api/v1/tipo-disponibilidades/:id","type":0,"val":"api","end":""},{"old":"/api/v1/tipo-disponibilidades/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/tipo-disponibilidades/:id","type":0,"val":"tipo-disponibilidades","end":""},{"old":"/api/v1/tipo-disponibilidades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tipo_disponibilidades.destroy']['types'],
  },
  'escala_trabalhos.import': {
    methods: ["POST"],
    pattern: '/api/v1/escala-trabalhos/import',
    tokens: [{"old":"/api/v1/escala-trabalhos/import","type":0,"val":"api","end":""},{"old":"/api/v1/escala-trabalhos/import","type":0,"val":"v1","end":""},{"old":"/api/v1/escala-trabalhos/import","type":0,"val":"escala-trabalhos","end":""},{"old":"/api/v1/escala-trabalhos/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['escala_trabalhos.import']['types'],
  },
  'escala_trabalhos.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/escala-trabalhos',
    tokens: [{"old":"/api/v1/escala-trabalhos","type":0,"val":"api","end":""},{"old":"/api/v1/escala-trabalhos","type":0,"val":"v1","end":""},{"old":"/api/v1/escala-trabalhos","type":0,"val":"escala-trabalhos","end":""}],
    types: placeholder as Registry['escala_trabalhos.index']['types'],
  },
  'escala_trabalhos.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/escala-trabalhos/create',
    tokens: [{"old":"/api/v1/escala-trabalhos/create","type":0,"val":"api","end":""},{"old":"/api/v1/escala-trabalhos/create","type":0,"val":"v1","end":""},{"old":"/api/v1/escala-trabalhos/create","type":0,"val":"escala-trabalhos","end":""},{"old":"/api/v1/escala-trabalhos/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['escala_trabalhos.create']['types'],
  },
  'escala_trabalhos.store': {
    methods: ["POST"],
    pattern: '/api/v1/escala-trabalhos',
    tokens: [{"old":"/api/v1/escala-trabalhos","type":0,"val":"api","end":""},{"old":"/api/v1/escala-trabalhos","type":0,"val":"v1","end":""},{"old":"/api/v1/escala-trabalhos","type":0,"val":"escala-trabalhos","end":""}],
    types: placeholder as Registry['escala_trabalhos.store']['types'],
  },
  'escala_trabalhos.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/escala-trabalhos/:id',
    tokens: [{"old":"/api/v1/escala-trabalhos/:id","type":0,"val":"api","end":""},{"old":"/api/v1/escala-trabalhos/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/escala-trabalhos/:id","type":0,"val":"escala-trabalhos","end":""},{"old":"/api/v1/escala-trabalhos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['escala_trabalhos.show']['types'],
  },
  'escala_trabalhos.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/escala-trabalhos/:id/edit',
    tokens: [{"old":"/api/v1/escala-trabalhos/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/escala-trabalhos/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/escala-trabalhos/:id/edit","type":0,"val":"escala-trabalhos","end":""},{"old":"/api/v1/escala-trabalhos/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/escala-trabalhos/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['escala_trabalhos.edit']['types'],
  },
  'escala_trabalhos.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/escala-trabalhos/:id',
    tokens: [{"old":"/api/v1/escala-trabalhos/:id","type":0,"val":"api","end":""},{"old":"/api/v1/escala-trabalhos/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/escala-trabalhos/:id","type":0,"val":"escala-trabalhos","end":""},{"old":"/api/v1/escala-trabalhos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['escala_trabalhos.update']['types'],
  },
  'escala_trabalhos.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/escala-trabalhos/:id',
    tokens: [{"old":"/api/v1/escala-trabalhos/:id","type":0,"val":"api","end":""},{"old":"/api/v1/escala-trabalhos/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/escala-trabalhos/:id","type":0,"val":"escala-trabalhos","end":""},{"old":"/api/v1/escala-trabalhos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['escala_trabalhos.destroy']['types'],
  },
  'slots.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/slots',
    tokens: [{"old":"/api/v1/slots","type":0,"val":"api","end":""},{"old":"/api/v1/slots","type":0,"val":"v1","end":""},{"old":"/api/v1/slots","type":0,"val":"slots","end":""}],
    types: placeholder as Registry['slots.index']['types'],
  },
  'slots.store': {
    methods: ["POST"],
    pattern: '/api/v1/slots',
    tokens: [{"old":"/api/v1/slots","type":0,"val":"api","end":""},{"old":"/api/v1/slots","type":0,"val":"v1","end":""},{"old":"/api/v1/slots","type":0,"val":"slots","end":""}],
    types: placeholder as Registry['slots.store']['types'],
  },
  'slots.import': {
    methods: ["POST"],
    pattern: '/api/v1/slots/import',
    tokens: [{"old":"/api/v1/slots/import","type":0,"val":"api","end":""},{"old":"/api/v1/slots/import","type":0,"val":"v1","end":""},{"old":"/api/v1/slots/import","type":0,"val":"slots","end":""},{"old":"/api/v1/slots/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['slots.import']['types'],
  },
  'slots.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/slots/:id',
    tokens: [{"old":"/api/v1/slots/:id","type":0,"val":"api","end":""},{"old":"/api/v1/slots/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/slots/:id","type":0,"val":"slots","end":""},{"old":"/api/v1/slots/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['slots.show']['types'],
  },
  'slots.update': {
    methods: ["PUT"],
    pattern: '/api/v1/slots/:id',
    tokens: [{"old":"/api/v1/slots/:id","type":0,"val":"api","end":""},{"old":"/api/v1/slots/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/slots/:id","type":0,"val":"slots","end":""},{"old":"/api/v1/slots/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['slots.update']['types'],
  },
  'slots.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/slots/:id',
    tokens: [{"old":"/api/v1/slots/:id","type":0,"val":"api","end":""},{"old":"/api/v1/slots/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/slots/:id","type":0,"val":"slots","end":""},{"old":"/api/v1/slots/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['slots.destroy']['types'],
  },
  'barras.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/barras',
    tokens: [{"old":"/api/v1/barras","type":0,"val":"api","end":""},{"old":"/api/v1/barras","type":0,"val":"v1","end":""},{"old":"/api/v1/barras","type":0,"val":"barras","end":""}],
    types: placeholder as Registry['barras.index']['types'],
  },
  'barras.create': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/barras/create',
    tokens: [{"old":"/api/v1/barras/create","type":0,"val":"api","end":""},{"old":"/api/v1/barras/create","type":0,"val":"v1","end":""},{"old":"/api/v1/barras/create","type":0,"val":"barras","end":""},{"old":"/api/v1/barras/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['barras.create']['types'],
  },
  'barras.store': {
    methods: ["POST"],
    pattern: '/api/v1/barras',
    tokens: [{"old":"/api/v1/barras","type":0,"val":"api","end":""},{"old":"/api/v1/barras","type":0,"val":"v1","end":""},{"old":"/api/v1/barras","type":0,"val":"barras","end":""}],
    types: placeholder as Registry['barras.store']['types'],
  },
  'barras.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/barras/:id',
    tokens: [{"old":"/api/v1/barras/:id","type":0,"val":"api","end":""},{"old":"/api/v1/barras/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/barras/:id","type":0,"val":"barras","end":""},{"old":"/api/v1/barras/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['barras.show']['types'],
  },
  'barras.edit': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/barras/:id/edit',
    tokens: [{"old":"/api/v1/barras/:id/edit","type":0,"val":"api","end":""},{"old":"/api/v1/barras/:id/edit","type":0,"val":"v1","end":""},{"old":"/api/v1/barras/:id/edit","type":0,"val":"barras","end":""},{"old":"/api/v1/barras/:id/edit","type":1,"val":"id","end":""},{"old":"/api/v1/barras/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['barras.edit']['types'],
  },
  'barras.update': {
    methods: ["PUT","PATCH"],
    pattern: '/api/v1/barras/:id',
    tokens: [{"old":"/api/v1/barras/:id","type":0,"val":"api","end":""},{"old":"/api/v1/barras/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/barras/:id","type":0,"val":"barras","end":""},{"old":"/api/v1/barras/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['barras.update']['types'],
  },
  'barras.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/barras/:id',
    tokens: [{"old":"/api/v1/barras/:id","type":0,"val":"api","end":""},{"old":"/api/v1/barras/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/barras/:id","type":0,"val":"barras","end":""},{"old":"/api/v1/barras/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['barras.destroy']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
